### ISSUE TITLE
Simpler Input Example

### ISSUE THREAD

**Issue by cart** [jamadazi/bevy-cookbook#1]
In general people should favor the `Input<T>` wrappers, which makes consumption much nicer for the common case of "checking if X is currently pressed". It would be good to encourage their use here.

https://github.com/bevyengine/bevy/blob/master/examples/input/keyboard_input.rs 
https://github.com/bevyengine/bevy/blob/master/examples/input/mouse_input.rs

**Comment by inodentry** [comment]
OK, I agree, I just didn't really know about this myself until now. When I was learning bevy, I kinda just saw events as "the versatile way to handle input" and ignored everything else.

I will update the input handling example. Your suggestion is in line with the intention of this project: to keep things as simple and as useful as possible. :)

**Comment by inodentry** [comment]
Speaking of which, I didn't cover `Input` in the cheatsheet either, so I will go add it there too.
